ports:
  web:
    port: 80
    nodePort: 30000

api:
  dashboard: true
  insecure: true

ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - web

ingressClass:
  enabled: true

service:
  type: NodePort

logs:
  general:
    level: INFO
  access:
    enabled: true
